# Generated by Django 3.0.6 on 2020-06-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiboSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num', models.IntegerField()),
                ('fibo_seq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NumbersAndSums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_num', models.IntegerField()),
                ('fibo_sums', models.TextField()),
            ],
        ),
    ]
