# Generated by Django 3.0.6 on 2020-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_path', models.TextField()),
                ('response_html', models.TextField()),
            ],
        ),
    ]
